name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull slimd12/data_extractor:latest
      - name: Delete old Docker container
        run: sudo docker rm -f data_extractor || true
      - name: Run Docker container
        run: sudo docker run -d -p 8000:8000 --name data_extractor slimd12/data_extractor
